#!/usr/bin/bash

STATUS=$(sudo netctl is-active vpn)

if [[ $STATUS == "active" ]] ; then
   sudo netctl stop vpn 
elif [[ $STATUS == "inactive" ]] ; then
   sudo netctl start vpn
elif [[ $STATUS == "error" ]] ; then
   sudo netctl stop vpn
   sleep 5
   sudo netctl start vpn
fi
